# # Arahkan MySQL ke H2 (In-Memory) agar Spring tidak mencari ke IP 192.168.1.246
# spring.datasource.mysql.driver-class-name=org.h2.Driver
# spring.datasource.mysql.jdbc-url=jdbc:h2:mem:mock_mysql;MODE=MySQL
# spring.datasource.mysql.username=sa
# spring.datasource.mysql.password=

# # PostgreSQL tetap ke local (asumsi tetap jalan)
# spring.datasource.pg.jdbc-url=jdbc:postgresql://localhost:5432/stok-anandam-local?reWriteBatchedInserts=true&sslmode=prefer
# spring.datasource.pg.username=postgres
# # Pakai env DB_PG_PASSWORD jika ada; kalau tidak, pakai default (hanya untuk dev)
# spring.datasource.pg.password=${DB_PG_PASSWORD:123}
# spring.datasource.pg.driver-class-name=org.postgresql.Driver
# spring.datasource.pg.maximum-pool-size=10
# spring.datasource.pg.max-lifetime=5400000